name: CI for Develop Branch

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      
jobs:
  automation_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print Workflow Details
        run: |
          echo "Workflow Name: ${{ github.workflow }}"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Commit Hash: ${{ github.sha }}"

  pull_request_job:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v4
      - name: Pull Request Job Execution
        run: |
          echo "Running additional checks for PR to develop branch"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "PR Body: ${{ github.event.pull_request.body }}"