name: CI for Main Branch (Production)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  automation_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Workflow Details
        run: |
          echo "Workflow Name: CI for Main Branch (Production)"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Commit Hash: ${{ github.sha }}"

  production_pull_request:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Print Pull Request Details
        run: |
          echo "Pull Request Number: ${{ github.event.number }}"
          echo "Pull Request Title: ${{ github.event.pull_request.title }}"
          echo "Pull Request Author: ${{ github.event.pull_request.user.login }}"
          echo "Pull Request Base Branch: ${{ github.event.pull_request.base.ref }}"
          echo "Pull Request Head Branch: ${{ github.event.pull_request.head.ref }}"
          echo "Pull Request Merge Commit: ${{ github.event.pull_request.head.sha }}"

  production_pull_request_closed:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    steps:
      - name: Print Closed Pull Request Details
        run: |
          echo "Closed Pull Request Number: ${{ github.event.number }}"
          echo "Closed Pull Request Title: ${{ github.event.pull_request.title }}"
          echo "Closed Pull Request Author: ${{ github.event.pull_request.user.login }}"
          echo "Closed Pull Request Base Branch: ${{ github.event.pull_request.base.ref }}"
          echo "Closed Pull Request Head Branch: ${{ github.event.pull_request.head.ref }}"
          echo "Closed Pull Request Merge Commit: ${{ github.event.pull_request.head.sha }}"
          echo "Closed Pull Request Merged: ${{ github.event.pull_request.merged }}"
